name: example
description: A sample command-line application.
version: 1.0.0
# repository: https://github.com/my_org/my_repo

environment:
  sdk: ^3.1.0

# Add regular dependencies here.
dependencies:
  js:
  annotations:
    path: ../annotations/
  widgets:
    path: ../widgets/

dev_dependencies:
  lints: ^3.0.0
  test: ^1.21.0
  build_runner:
  generators:
    path: ../generators/
