name: example
description: A sample Flyer application.
version: 1.0.0
# repository: https://github.com/my_org/my_repo

environment:
  sdk: ^3.4.0

# Add regular dependencies here.
dependencies:
  # path: ^1.9.0
  flyer:
    path: ../

dev_dependencies:
  lints: 4.0.0
  test: 1.25.8
