name: flyer
description: Framework for creating web pages in Dart language
repository: https://github.com/FlyerWebFramework/flyer
version: 0.2.0

environment:
  sdk: ^3.3.0

# Add regular dependencies here.
dependencies:
  path: 1.9.0
  dcli: 4.0.1-beta.4
  freezed: 2.5.2
  freezed_annotation: 2.4.1
  color:
    git: git@github.com:FlyerWebFramework/Color.git

dev_dependencies:
  lints: 3.0.0
  test: 1.25.4
  build_runner: 2.4.9
