name: flyer
description: A starting point for Dart libraries or applications.
version: 0.0.1
# repository: https://github.com/my_org/my_repo

environment:
  sdk: ^3.1.0

# Add regular dependencies here.
dependencies:
  path: ^1.9.0
  dcli: ^3.2.3
  freezed: ^2.4.6
  freezed_annotation: 2.4.1
  color:
    git: git@github.com:FlutterPackages/Color.git

dev_dependencies:
  lints: ^2.0.0
  test: ^1.21.0
  build_runner: ^2.4.7
