name: flyer
description: Framework for creating web pages in Dart language
repository: https://github.com/FlyerWebFramework/flyer
version: 0.1.0

environment:
  sdk: ^3.1.0

# Add regular dependencies here.
dependencies:
  path: ^1.9.0
  dcli: ^3.2.3
  freezed: ^2.4.6
  freezed_annotation: 2.4.1
  color:
    git: git@github.com:FlyerWebFramework/Color.git

dev_dependencies:
  lints: ^3.0.0
  test: ^1.21.0
  build_runner: ^2.4.7
